### ISSUE TITLE
truncate_words removed from django 1.6

### ISSUE THREAD

**Issue by prudnitskiy** [adw0rd/marcus#26]
So if you'll update django to 1.6 branch, Marcus completely brokes your installation with this error

```
    from django.utils.text import truncate_words
    ImportError: cannot import name truncate_words
```

**Comment by adw0rd** [comment]
It's fixed [here](https://github.com/adw0rd/marcus/commit/f4f7bd51538875dc5fa0f02aab9e003c01fd80a7)
