### ISSUE TITLE
database error on any comment operation using pgsql

### ISSUE THREAD

**Issue by prudnitskiy** [adw0rd/marcus#28]
```
column "marcus_comment.id" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: SELECT "marcus_comment"."id", "marcus_comment"."article_id",...
```

On any comment operation (creating, approval, editing).

Django==1.5.12
psycopg2==2.6

**Comment by adw0rd** [comment]
@prudnitskiy what about PostgreSQL version?

**Comment by prudnitskiy** [comment]
Client: 9.4 (9.2.10-1.pgdg70+1)
Server: 9.2 (9.4.1-1.pgdg70+1)

**Comment by adw0rd** [comment]
May be, your problem is decided here https://github.com/adw0rd/marcus/pull/25
